import { defineComponent, h, ref } from 'vue'

/**
 * ReportExport — accountants do not finish at the screen. They finish when the
 * client, the file and sometimes the bank all hold the same document. Same
 * optimised position, laid out to be read on paper.
 */
const PAGES = [
  {
    title: 'Group Optimiser: Southland Consolidated Group',
    lead: 'Please see the outstanding transactions for each taxpayer in the group below.',
    rows: [
      ['Southland Holdings', 'Transfer in', '$248,400'],
      ['Waihopai Transport', 'Transfer out', '$92,600'],
      ['Ōtautau Logistics', 'Transfer in', '$61,250'],
      ['Riverton Property', 'Transfer out', '$145,900'],
      ['Tuatapere Farming', 'Transfer in', '$18,900'],
      ['Colac Bay Rentals', 'Transfer out', '$12,670'],
    ],
    note: 'One page for the group. The accountant sends this one to the client.',
  },
  {
    title: 'Group Optimiser: Taxpayer Name (000 000 000)',
    lead: 'This is the remaining tax to buy for this year and must be paid before the taxpayer’s 75 day deadline.',
    rows: [
      ['28 Aug 2022', 'Purchase', '$4,120'],
      ['15 Jan 2023', 'Purchase', '$5,600'],
      ['07 May 2023', 'Transfer to IRD', '$2,660'],
    ],
    note: 'Then a page per taxpayer, broken down by tax date. This is the one that goes in the client file.',
  },
  {
    title: 'Payment',
    lead: 'Please use the following details for online banking.',
    rows: [
      ['Payee', 'TMNZ Guardian Trust Tax Pool', ''],
      ['Reference', 'Group 4471', ''],
      ['Amount', '$12,380', 'or pay what you want, when you want, using Flexitax'],
    ],
    note: 'And the page that actually gets money to move. Everything a bank transfer needs, and nothing it does not.',
  },
]

export default defineComponent({
  name: 'ReportExport',
  setup() {
    const at = ref(0)
    const p = () => PAGES[at.value]

    return () =>
      h('div', { class: 'go-report' }, [
        h('div', { class: 'go-paper' }, [
          h('div', { class: 'go-paper-head' }, [
            h('h5', null, p().title),
            h('span', null, 'First Lastname · 13/09/2024'),
          ]),
          h('p', { class: 'go-paper-lead' }, p().lead),
          h('table', { class: 'go-paper-table' }, [
            h('tbody', null, p().rows.map(r =>
              h('tr', { key: r[0] }, r.map((cell, i) =>
                h('td', { key: i, class: i === 2 ? 'go-num' : '' }, cell)
              ))
            )),
          ]),
          h('p', { class: 'go-paper-foot' }, `Page ${at.value + 1} of ${PAGES.length}. Group Optimiser. Generated by First Lastname on 13/09/2024.`),
        ]),

        h('div', { class: 'go-pager' }, [
          h('button', { class: 'go-step', disabled: at.value === 0, onClick: () => { at.value -= 1 } }, '‹'),
          h('span', null, `${at.value + 1} / ${PAGES.length}`),
          h('button', { class: 'go-step', disabled: at.value === PAGES.length - 1, onClick: () => { at.value += 1 } }, '›'),
        ]),

        h('p', { class: 'cs-note' }, p().note),
      ])
  },
})
